version: '3.8'
services:
  video-converter:
    build:
      context: ../../
      dockerfile: apps/docker/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./downloads:/app/public/downloads
    environment:
      - PORT=3001
    restart: unless-stopped
